browsers:
  chrome: 'chrome'
  firefox: 'firefox'
  brave: 'brave'
  mobile: 'mobile'

dir_name:
  date_one: '08_12_2022'
  date_two: '03_29_2023'
  date_three: '00_00_0000'

dir_paths:
  cd: '../../../'
  cd_src: '../../../src/'
  cd_pipeline: '../../../pipeline_functions/'
  chrome_old_models: 'models/chrome/08_12_2022'

browser_object:
  chrome_old:
    browser: 'chrome'
    date: '08_12_2022'
  chrome_new:
    browser: 'chrome'
    date: '03_29_2023'
  firefox:
    browser: 'firefox'
    date: '08_12_2022'
  brave:
    browser: 'brave'
    date: '08_12_2022'

browser_object_parsed:
  chrome_old_test:
    browser: 'chrome'
    date: '08_12_2022'
    file_name: 'test_set'
    other_data_set_bool: False
  chrome_old_calibration:
    browser: 'chrome'
    date: '08_12_2022'
    file_name: 'calibration_set'
    other_data_set_bool: False
  chrome_new:
    browser: 'chrome'
    date: '03_29_2023'
    file_name: 'merged_data'
    other_data_set_bool: True
  firefox:
    browser: 'firefox'
    date: '08_12_2022'
    file_name: 'merged_data'
    other_data_set_bool: True
  brave:
    browser: 'brave'
    date: '08_12_2022'
    file_name: 'merged_data'
    other_data_set_bool: True

browser_object_parsed_exp_google:
  chrome_old_test:
    browser: 'chrome'
    date: '08_12_2022'
    file_name: 'test_set'
    other_data_set_bool: False
  chrome_old_calibration:
    browser: 'chrome'
    date: '08_12_2022'
    file_name: 'calibration_set'
    other_data_set_bool: False
  chrome_old_google:
    browser: 'chrome'
    date: '08_12_2022'
    file_name: 'google_set'
    other_data_set_bool: False

browser_object_feature_engineering:
  chrome_old_train:
    browser: 'chrome'
    date: '08_12_2022'
    file_name: 'train_set'
  chrome_old_test:
    browser: 'chrome'
    date: '08_12_2022'
    file_name: 'test_set'
  chrome_old_calibration:
    browser: 'chrome'
    date: '08_12_2022'
    file_name: 'calibration_set'
  chrome_new:
    browser: 'chrome'
    date: '03_29_2023'
    file_name: 'merged_data'
  firefox:
    browser: 'firefox'
    date: '08_12_2022'
    file_name: 'merged_data'
  brave:
    browser: 'brave'
    date: '08_12_2022'
    file_name: 'merged_data'

browser_object_feature_engineering_exp_google:
  chrome_old_train:
    browser: 'chrome'
    date: '08_12_2022'
    file_name: 'train_set'
  chrome_old_test:
    browser: 'chrome'
    date: '08_12_2022'
    file_name: 'test_set'
  chrome_old_calibration:
    browser: 'chrome'
    date: '08_12_2022'
    file_name: 'calibration_set'
  chrome_old_google:
    browser: 'chrome'
    date: '08_12_2022'
    file_name: 'google_set'

browser_object_evaluation:
  chrome_old_test:
    browser: 'chrome'
    date: '08_12_2022'
    file_name: 'test_set'
  chrome_old_calibration:
    browser: 'chrome'
    date: '08_12_2022'
    file_name: 'calibration_set'
  chrome_new:
    browser: 'chrome'
    date: '03_29_2023'
    file_name: 'merged_data'
  firefox:
    browser: 'firefox'
    date: '08_12_2022'
    file_name: 'merged_data'
  brave:
    browser: 'brave'
    date: '08_12_2022'
    file_name: 'merged_data'

browser_object_evaluation_exp_google:
  chrome_old_test:
    browser: 'chrome'
    date: '08_12_2022'
    file_name: 'test_set'
  chrome_old_calibration:
    browser: 'chrome'
    date: '08_12_2022'
    file_name: 'calibration_set'
  chrome_old_google:
    browser: 'chrome'
    date: '08_12_2022'
    file_name: 'google_set'